name: Deploy Backend

on:
  push:
    branches: [main]
    # paths:
    #   - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            
            # Navigate to the backend folder
            cd /var/www/backend
            
            # Pull the latest code
            git pull origin main
            
            # Install any new dependencies
            npm install
            
            # Inject the latest Secrets into .env (In case they changed)
            # echo "NODE_ENV=production" >> .env
            
            # Restart the existing PM2 process
            pm2 restart backend-api
            pm2 save