name: Deploy Backend

on:
  push:
    branches: [main]
    # paths:
    #   - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Check if directory exists
            if [ ! -d "/var/www/backend" ]; then
              sudo mkdir -p /var/www/backend
              sudo chown -R ubuntu:ubuntu /var/www/backend
              git clone https://github.com/${{ github.repository }}.git /var/www/backend
            fi
            
            cd /var/www/backend/backend
            git pull origin main
            npm install
            
            # Create/Update .env file
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
            
            # Smart restart with PM2
            pm2 restart backend-api --update-env || pm2 start index.js --name "backend-api"
            pm2 save